vint: 
  config_path: "../../train/config/vint.yaml"
  ckpt_path: "../model_weights/vint.pth"

late_fusion: 
  config_path: "../../train/config/late_fusion.yaml"
  ckpt_path: "../model_weights/vint_late_fusion.pth"

# gnm: 
#   config_path: "../../train/config/gnm.yaml"
#   ckpt_path: "../model_weights/gnm_large.pth"

GNM: 
  config_path: "../../../omnimimic/policy_config/gnmv9_policy.yaml"
  ckpt_path: "../model_weights/policy_epoch_70_seed_50.ckpt"

nomad: 
  config_path: "../../train/config/nomad.yaml"
  ckpt_path: "../model_weights/nomad.pth"


# add your own model configs here after saving the *.pth file to ../model_weight