vint: 
  config_path: "../../train/config/vint.yaml"
  ckpt_path: "../model_weights/vint.pth"

late_fusion: 
  config_path: "../../train/config/late_fusion.yaml"
  ckpt_path: "../model_weights/vint_late_fusion.pth"

# gnm: 
#   config_path: "../../train/config/gnm.yaml"
#   ckpt_path: "../model_weights/gnm_large.pth"

GNM: 
  config_path: "../../../omnimimic/policy_config/gnmv9_policy_test.yaml"
  ckpt_path: "../model_weights/policy_epoch_75_seed_50.ckpt"

vintrlds: 
  config_path: "../../train/config/vintrlds.yaml"
  ckpt_path: "../model_weights/69.pth"

vintnorlds: 
  config_path: "../../train/config/vintnorlds.yaml"
  ckpt_path: "../model_weights/50.pth"

nomad: 
  config_path: "../../train/config/nomad.yaml"
  ckpt_path: "../model_weights/nomad.pth"


# add your own model configs here after saving the *.pth file to ../model_weight